from django.urls import path
from . import views

urlpatterns = [
    # Dashboard endpoints
    path('dashboard/stats/', views.dashboard_stats, name='dashboard_stats'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/update/', views.user_profile_update, name='user_profile_update'),
    path('profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
    path('customer-profile/me/', views.current_customer_profile, name='current_customer_profile'),
    path('customer-profile/me/update/', views.current_customer_profile_update, name='current_customer_profile_update'),
    path('customer-profile/me/upload-image/', views.customer_profile_upload_image, name='customer_profile_upload_image'),
    path('customer-profile/provider/bookings/<int:booking_id>/', views.provider_view_customer_profile, name='provider_view_customer_profile'),
    
    # Service endpoints
    path('categories/', views.service_categories, name='service_categories'),
    path('providers/', views.providers_list, name='providers_list'),
    path('providers/<int:provider_id>/', views.provider_detail, name='provider_detail'),
    # Distinct district/city values from providers (dynamic; not hardcoded)
    path('locations/districts/', views.location_districts, name='location_districts'),
    path('locations/cities/', views.location_cities, name='location_cities'),
    path('services/', views.services_list, name='services_list'),
    path('bookings/upload-request-image/', views.upload_booking_request_image, name='upload_booking_request_image'),
    path('service-category-requests/create/', views.create_service_category_request, name='create_service_category_request'),
    path('bookings/create/', views.create_booking, name='create_booking'),
    path('bookings/', views.user_bookings, name='user_bookings'),
    path('bookings/<str:booking_id>/update/', views.update_booking_status, name='update_booking_status'),
    path('bookings/<str:booking_id>/', views.booking_detail, name='booking_detail'),
    path('reviews/create/', views.create_review, name='create_review'),
    path('reviews/', views.my_reviews, name='my_reviews'),
    path('reviews/booking/<int:booking_id>/', views.review_for_booking, name='review_for_booking'),
    path('reviews/received/', views.provider_reviews, name='provider_reviews'),
    path('notifications/', views.provider_notifications, name='provider_notifications'),
    path('customer-notifications/', views.customer_notifications, name='customer_notifications'),
    path('provider-time-slots/', views.provider_time_slots, name='provider_time_slots'),
    path('provider-time-slots/<int:slot_id>/', views.provider_time_slot_detail, name='provider_time_slot_detail'),
    path('promotional-banners/', views.promotional_banners_list, name='promotional_banners_list'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('favorites/summary/', views.favorites_summary, name='favorites_summary'),
    path('favorites/providers/', views.favorite_providers_list, name='favorite_providers_list'),
    path('favorites/providers/add/', views.favorite_provider_add, name='favorite_provider_add'),
    path('favorites/providers/<int:provider_id>/', views.favorite_provider_remove, name='favorite_provider_remove'),
    path('favorites/services/', views.favorite_services_list, name='favorite_services_list'),
    path('favorites/services/add/', views.favorite_service_add, name='favorite_service_add'),
    path('favorites/services/<int:service_id>/', views.favorite_service_remove, name='favorite_service_remove'),
    path('referral-profile/', views.referral_profile, name='referral_profile'),
    path('provider-verifications/', views.provider_verifications_list, name='provider_verifications_list'),
    path('provider-verifications/status/', views.provider_verification_status, name='provider_verification_status'),
    path('provider-verifications/create/', views.provider_verification_create, name='provider_verification_create'),
    path('provider-verifications/<int:verification_id>/', views.provider_verification_delete, name='provider_verification_delete'),
    path('provider-verifications/applications/', views.provider_verification_applications, name='provider_verification_applications'),
    path('provider-verifications/applications/<int:provider_id>/review/', views.provider_verification_review, name='provider_verification_review'),
    path('payments/initiate/', views.payment_initiate, name='payment_initiate'),
    path('payments/verify-complete/', views.payment_verify_complete, name='payment_verify_complete'),
    path('payments/esewa-success/', views.payment_esewa_success, name='payment_esewa_success'),
    path('payments/esewa-failure/', views.payment_esewa_failure, name='payment_esewa_failure'),
    path('payments/demo-complete/', views.payment_demo_complete, name='payment_demo_complete'),
    path('wallet/', views.wallet_summary, name='wallet_summary'),
    path('receipts/', views.receipts_list, name='receipts_list'),
    path('receipts/<int:receipt_id>/', views.receipt_detail, name='receipt_detail'),
    path('receipts/booking/<int:booking_id>/', views.receipt_by_booking, name='receipt_by_booking'),
    path('refunds/', views.refund_list, name='refund_list'),
    path('refunds/<int:refund_id>/provider-review/', views.refund_provider_review, name='refund_provider_review'),
    path('refunds/<int:refund_id>/review/', views.refund_review, name='refund_review'),

    # Chat endpoints
    path('chat/threads/', views.chat_threads, name='chat_threads'),
    path('chat/threads/<int:booking_id>/messages/', views.chat_messages, name='chat_messages'),
    path('chat/threads/<int:booking_id>/messages/<int:message_id>/delete/', views.delete_chat_message, name='delete_chat_message'),

    # Google Maps / Places proxy (API key server-side)
    path('places/autocomplete/', views.places_autocomplete, name='places_autocomplete'),
    path('places/details/', views.place_details, name='place_details'),
    path('places/reverse-geocode/', views.reverse_geocode, name='reverse_geocode'),
]

