-- Run in Supabase SQL editor: customer profile table used by app and provider booking flow.
CREATE TABLE IF NOT EXISTS seva_customer_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES seva_auth_user(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  location TEXT,
  profile_image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_seva_customer_profile_user_id ON seva_customer_profile(user_id);

COMMENT ON TABLE seva_customer_profile IS 'Customer profile details editable by customer and visible to providers for related bookings.';
COMMENT ON COLUMN seva_customer_profile.user_id IS 'One-to-one link to seva_auth_user.';
COMMENT ON COLUMN seva_customer_profile.full_name IS 'Customer display name required for profile.';
COMMENT ON COLUMN seva_customer_profile.location IS 'Optional free-text customer location/address.';
COMMENT ON COLUMN seva_customer_profile.profile_image_url IS 'Signed or public URL to customer profile image.';

CREATE OR REPLACE FUNCTION set_seva_customer_profile_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_seva_customer_profile_updated_at ON seva_customer_profile;
CREATE TRIGGER trg_seva_customer_profile_updated_at
BEFORE UPDATE ON seva_customer_profile
FOR EACH ROW
EXECUTE FUNCTION set_seva_customer_profile_updated_at();
