-- Provider availability slots for booking flow
create table if not exists public.seva_provider_time_slot (
    id bigint generated by default as identity primary key,
    provider_id bigint not null references public.seva_auth_user(id) on delete cascade,
    slot_date date not null,
    day_name text not null,
    start_time time not null,
    end_time time not null,
    note text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_seva_provider_time_slot_provider_date
    on public.seva_provider_time_slot (provider_id, slot_date);

create index if not exists idx_seva_provider_time_slot_active
    on public.seva_provider_time_slot (provider_id, is_active, slot_date);
