# Generated by Django 6.0 on 2026-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamro_Seva', '0002_service_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='profession',
            field=models.CharField(choices=[('CARPENTER', 'Carpenter'), ('ELECTRICIAN', 'Electrician'), ('CLEANING', 'House Cleaning'), ('PAINTING', 'Painting'), ('PLUMBING', 'Plumbing'), ('HAIR_STYLIST', 'Hair Stylist')], default='CARPENTER', max_length=30),
        ),
    ]
