# Generated by Django 6.0 on 2026-01-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamro_Seva', '0003_remove_serviceproviderprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='profession',
            field=models.CharField(choices=[('CARPENTER', 'Carpenter'), ('ELECTRICIAN', 'Electrician'), ('HOUSE_CLEANING', 'House Cleaning'), ('PAINTER', 'Painter'), ('PLUMBER', 'Plumber'), ('HAIR_STYLIST', 'Hair Stylist')], default='CARPENTER', max_length=30),
        ),
    ]
